### ISSUE TITLE
Pen Support / variable witdh stroke / Palm Rejection

### ISSUE THREAD

**Issue by evlli** [SimpleMobileTools/Simple-Draw#199] opened 2021-08-06 08:43 UTC
This is probably a pretty huge scope for a single issue, sorry.
I'm not very experienced with android apps, but I would like to contribute this, though I'll definitely need some pointers on good resources.

**Comment by tibbi** [comment] 2021-08-06 10:52
Im not aware of any resources, could just Google too. Duplicate of #139

**Closed by tibbi** 2021-08-06 10:52 UTC
