### ISSUE TITLE
Opened image disappears on device screen rotation.

### ISSUE THREAD

**Issue by iamank1t** [SimpleMobileTools/Simple-Draw#96] opened 2018-03-23 22:26 UTC
#### Expected behavior
I opened image in app to draw something on image. After opening image file, if i rotate my device from portrait to landscape or landscape to portrait, the app needs to keep the opened image not to remove them from my canvas.

#### Actual behavior
I opened image in app to draw something on image. Now the image is on my canvas, if i rotate my device from portrait to landscape or landscape to portrait, the image just disappears from my canvas.

#### How to reproduce
To reproduce the bug, follow the following steps :-
- Download app from playstore or f-droid.
- Open app and click on three dots on top right of app nav bar. A menu will appear, now select open file from menu and choose any image from your device gallery.
- Now you see your image is on canvas. Now rotate your screen from portrait to landscape or landscape to portrait and the image got disappears and don't came back.

<pre><code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v3.1.5
</code></pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=O5VAG4lyZgY
    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/opened-image-disappears-on-device-screen-rotation">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment] 2018-03-31 18:37
duplicate of #95

**Closed by tibbi** 2018-03-31 18:37 UTC
Labels: bug
